server:
  port: 1234

spring:
  application:
    name: klist

  profiles:
    active: local

  jpa:
    open-in-view: false

weather:
  api:
    base-url: https://apihub.kma.go.kr/api/typ02/openApi/VilageFcstInfoService_2.0